# Site Settings
title: Jekflix | A theme for Jekyll
email: pawel.html@gmail.com
description: JavaScript blog.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://github.com/pawellesniowski" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"

# User Settings
username: Jekflix
user_description: Some text about you.
disqus_username: disqus_username

# Social Media
# Remove the item if you don't need it
github_username: pawellesniowski
facebook_username: facebook_username
twitter_username: twitter_username
instagram_username: instagram_username
linkedin_username: pawellesniowski


# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']

theme: jekyll-theme-hacker